client_index:
    path:     /profil
    defaults: { _controller: "LimitlessKarhabtiBundle:Client:index" }
    methods:  GET

client_show:
    path:     /{id}/show
    defaults: { _controller: "LimitlessKarhabtiBundle:Client:show" }
    methods:  GET

client_new:
    path:     /new
    defaults: { _controller: "LimitlessKarhabtiBundle:Client:new" }
    methods:  [GET, POST]

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "LimitlessKarhabtiBundle:Client:edit" }
    methods:  [GET, POST]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "LimitlessKarhabtiBundle:Client:delete" }
    methods:  DELETE
client_Home:
    path:    /home
    defaults: { _controller: "LimitlessKarhabtiBundle:Client:home" }

client_offre_index:
    path:     /offres
    defaults: { _controller: "LimitlessKarhabtiBundle:Offre:findClient" }

Clientreserve_offre_index:
    path:     /reserverOffre
    defaults: { _controller: "LimitlessKarhabtiBundle:ReservationOffre:index" }
    methods:  GET
Clientreserve_pack_index:
    path:     /reserverPack
    defaults: { _controller: "LimitlessKarhabtiBundle:Pack:affichepack"}
