superadmin_modele_index:
    path:     /
    defaults: { _controller: "LimitlessKarhabtiBundle:Modele:index" }
    methods:  GET

superadmin_modele_show:
    path:     /{id}/show
    defaults: { _controller: "LimitlessKarhabtiBundle:Modele:show" }
    methods:  GET

superadmin_modele_new:
    path:     /new
    defaults: { _controller: "LimitlessKarhabtiBundle:Modele:new" }
    methods:  [GET, POST]

superadmin_modele_edit:
    path:     /{id}/edit
    defaults: { _controller: "LimitlessKarhabtiBundle:Modele:edit" }
    methods:  [GET, POST]

superadmin_modele_delete:
    path:     /{id}/delete
    defaults: { _controller: "LimitlessKarhabtiBundle:Modele:delete" }
    methods:  DELETE
