limitless_karhabti_homepage:
    path:     /
    defaults: { _controller: LimitlessKarhabtiBundle:Default:index }
test:
    path:     /test
    defaults: { _controller: LimitlessKarhabtiBundle:Default:test }
AffichageMoniteur:
    path:     /listeMoniteur
    defaults: { _controller: LimitlessKarhabtiBundle:Moniteur:Affichage }

moniteur_tache_index:
    path:     /listeTache
    defaults: { _controller: LimitlessKarhabtiBundle:Tache:listMoniteur }

moniteur_client_index:
    path:     /listeClient
    defaults: { _controller: LimitlessKarhabtiBundle:Tache:listMoniteurClient }


DeleteMoniteur:
    path:     /DeleteMoniteur/{id}
    defaults: { _controller: LimitlessKarhabtiBundle:Moniteur:Delete }

UpdateMoniteur:
    path:     /update/{id}
    defaults: { _controller: LimitlessKarhabtiBundle:Moniteur:Update }

moniteur_index:
    path:     /profil
    defaults: { _controller: "LimitlessKarhabtiBundle:Moniteur:index" }
    methods:  GET

moniteur_agence_index:
    path:     /agences
    defaults: { _controller: "LimitlessKarhabtiBundle:Moniteur:rechercheAgence" }