responsable_pack_new:
     path:     /add
     defaults: { _controller: "LimitlessKarhabtiBundle:Pack:addpack" }


responsable_pack_index:
    path:     /
    defaults: { _controller: "LimitlessKarhabtiBundle:Pack:findpack"}

responsable_pack_show:
    path:     /{id}/show
    defaults: { _controller: "LimitlessKarhabtiBundle:Pack:showpack" }

responsable_pack_delete:
    path:     /delete/{id}
    defaults: { _controller: "LimitlessKarhabtiBundle:Pack:deletepack" }


responsable_pack_edit:
    path:     /update/{id}
    defaults: { _controller: "LimitlessKarhabtiBundle:Pack:updatepack" }

