client_reservationpack_index:
    path:     /
    defaults: { _controller: "LimitlessKarhabtiBundle:ReservationPack:index" }
    methods:  GET

client_reservationpack_show:
    path:     /{id}/show
    defaults: { _controller: "LimitlessKarhabtiBundle:ReservationPack:show" }
    methods:  GET

client_reservationpack_new:
    path:     /new/{id}
    defaults: { _controller: "LimitlessKarhabtiBundle:ReservationPack:new" }
    methods:  [GET, POST]

client_reservationpack_edit:
    path:     /{id}/edit
    defaults: { _controller: "LimitlessKarhabtiBundle:ReservationPack:edit" }
    methods:  [GET, POST]

client_reservationpack_delete:
    path:     /{id}/delete
    defaults: { _controller: "LimitlessKarhabtiBundle:ReservationPack:delete" }
    methods:  DELETE
