reponsable_tache_index:
    path:     /
    defaults: { _controller: "LimitlessKarhabtiBundle:Tache:recherche" }

reponsable_tache_new:
    path:     /new
    defaults: { _controller: "LimitlessKarhabtiBundle:Tache:new" }
    methods:  [GET, POST]

reponsable_tache_edit:
    path:     /{id}/edit
    defaults: { _controller: "LimitlessKarhabtiBundle:Tache:edit" }
    methods:  [GET, POST]

reponsable_tache_delete:
    path:     /{id}/delete
    defaults: { _controller: "LimitlessKarhabtiBundle:Tache:delete" }
    methods:  DELETE



